version: 2.1
jobs:
  build:
    docker:
      - image: jrrr/esp32-ci:6721a663f1b1d48ba2e3b306436e52605976af8b
      # Espressif has a docker image! espressif/esp32-ci-env
      # but it's out of date:
      # WARNING: Toolchain version is not supported: 1.22.0-61-gab8375a
      # Expected to see version: 1.22.0-80-g6c4433a
    environment:
      CCACHE_DISABLE: true
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: xtensa-esp32-elf-gcc --version
      - run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=amazon-freertos/tools/cmake/toolchains/xtensa-esp32.cmake -GNinja
      - run: cmake --build build

      # - run:
      #     name: Build
      #     command: cd make; make all
      # - run:
      #     name: Test
      #     command: cd test; make
