AMAZON_FREERTOS_LIB_DIR := ../amazon-freertos/lib

COMPONENT_NAME="ROOMMATE"

ROOMMATE_BOARD_INCLUDE = ../$(TARGET_BOARD_FROM_ROOT)
COMPONENT_PRIV_INCLUDEDIRS := $(AMAZON_FREERTOS_LIB_DIR)/third_party/pkcs11 $(ROOMMATE_BOARD_INCLUDE)

